title: Binja Lysa
<p float="right">
  <img src="https://github.com/lysabinja14-saly/portfolio/blob/main/Binja%20LysaProfilephoto.jpg" width="120" />
</p>
# Hi, 👋
Welcome to my portfolio!
theme: jekyll-theme-minimal
